apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app-deployment
  labels:
    app: fastapi
    tier: api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fastapi
      tier: api
  template:
    metadata:
      labels:
        app: fastapi
        tier: api
    spec:
      containers:
      - name: fastapi-app
        image: amalkuriakose/fastapi:log
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
      imagePullSecrets:
      - name: docker-hub-creds