loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: s3
      schema: v13
  storage:
    type: 's3'
    s3:
      region: ap-south-1
      endpoint: s3.ap-south-1.amazonaws.com
      secretAccessKey: xxxxx # Do not use in production
      accessKeyId: xxxxx # Do not use in production
    bucketNames:
      chunks: loki-chunks-12345
      ruler: loki-ruler-12345
      admin: loki-admin-12345
      s3ForcePathStyle: false
      insecure: false

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

chunksCache:
  allocatedMemory: 1024