apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: fastapi
    tier: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000