 global: {}
    receivers:
    - name: default-receiver
    - name: send-email
      email_configs:
      - to: test@mail.com
        from: test@mail.com
        smarthost: smtp.mail.com:465
        auth_username: test@mail.com
        auth_password: test-password
        text: "App Down"
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
      routes:
        - matchers:
            - team="devops"
            - severity="critical"
          receiver: send-email
          continue: true
    templates:
    - /etc/alertmanager/*.tmpl